apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blogtv
spec:
  selector:
    app: blogtv
  ports:
    - protocol: TCP
      port: 80
      name: http
  type: LoadBalancer    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogtv
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogtv
  template:
    metadata:
      labels:
        app: hbvue
    spec:
      containers:
      - name: blogtv
        image: lucarv/blogtv:latest
        ports:
        - containerPort: 80
